---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, alarms, cloudwatch, giveback, govcloud, detaching, encryption, snapmanager, features 
summary: As limitações conhecidas identificam plataformas, dispositivos ou funções que não são suportadas por esta versão do produto ou que não interoperam corretamente com ele. Revise essas limitações com cuidado. 
---
= Limitações conhecidas
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
As limitações conhecidas identificam plataformas, dispositivos ou funções que não são suportadas por esta versão do produto ou que não interoperam corretamente com ele. Revise essas limitações com cuidado.



== Limitações gerais

As limitações a seguir se aplicam ao ONTAP Cloud na AWS e no Azure.



=== Máximo de operações de replicação simultânea

O número máximo de transferências simultâneas de SnapMirror ou SnapVault para Cloud Volumes ONTAP é de 100 por nó, independentemente do tipo de instância ou do tipo de máquina.



=== As atualizações de software devem ser concluídas pelo Cloud Manager

As atualizações do Cloud Volumes ONTAP devem ser concluídas a partir do Cloud Manager. Você não deve atualizar o Cloud Volumes ONTAP usando o Gerenciador de sistema ou a CLI. Isso pode afetar a estabilidade do sistema.



=== A criptografia não é suportada em discos de inicialização e raiz

Se você ativou uma opção do seu provedor de nuvem que criptografa automaticamente todos os novos volumes ou discos, desative essa opção temporariamente ao implantar o ONTAP Cloud. Se você não fizer isso, então a implantação do ONTAP Cloud falhará. A criptografia não é suportada nos discos de inicialização e raiz do sistema ONTAP Cloud.



=== A implantação do ONTAP Cloud não deve ser modificada a partir do console do seu provedor de nuvem

As alterações em uma configuração da nuvem ONTAP a partir do console do seu provedor de nuvem resultam em uma configuração não suportada. Qualquer alteração nos recursos de nuvem do ONTAP que o Cloud Manager cria e gerencia pode afetar a estabilidade do sistema e a capacidade do Cloud Manager de gerenciar o sistema.



=== Os discos e agregados devem ser gerenciados no Cloud Manager

Todos os discos e agregados devem ser criados e excluídos diretamente do Cloud Manager. Você não deve executar essas ações de outra ferramenta de gerenciamento. Isso pode afetar a estabilidade do sistema, dificultar a capacidade de adicionar discos no futuro e, potencialmente, gerar taxas redundantes de provedores de nuvem.



=== Limitação de licenciamento do SnapManager

As licenças SnapManager por servidor são suportadas com o ONTAP Cloud. As licenças por sistema de storage (pacote SnapManager) não são suportadas.



=== Funcionalidades ONTAP não suportadas

Os recursos a seguir não são compatíveis com o ONTAP Cloud:

* Deduplicação in-line de nível de agregado
* Deduplicação em segundo plano de nível de agregado
* Centro de manutenção do disco
* Sanitização de disco
* Fibre Channel (FC)
* Piscinas flash
* FlexCache
* Volumes FlexGroup
* Volumes infinitos
* Grupos de interfaces
* Failover de LIF Intranode
* MetroCluster
* Alocação a vários clientes (apenas um SVM com serviço de dados é compatível)
* Criptografia de volume do NetApp
* RAID4, RAID-DP, RAID-TEC (RAID0 é suportado)
* Processador de serviço
* SnapLock
* SnapMirror síncrono
* VLANs




== Limitações conhecidas da nuvem ONTAP na AWS

As limitações conhecidas a seguir afetam a nuvem ONTAP na AWS.



=== Alarmes falsos relatados pelo Amazon CloudWatch

O ONTAP Cloud não libera CPUs quando ociosas, portanto, o Amazon CloudWatch pode relatar um aviso de CPU alto para a instância do EC2 porque ele vê 100% de uso. Pode ignorar este alarme. O comando ONTAP statistics exibe o verdadeiro uso das CPUs.



=== Os pares de HA na nuvem da ONTAP não são compatíveis com storage imediato

Depois que um nó é reiniciado, o parceiro deve sincronizar os dados antes que ele possa retornar o armazenamento. O tempo necessário para sincronizar os dados depende da quantidade de dados gravados pelos clientes enquanto o nó estava inativo e da velocidade de gravação de dados durante o tempo de giveback.



=== Limitações com a região AWS GovCloud (EUA)

* O Cloud Manager deve ser implantado em uma região do AWS GovCloud (EUA) se você quiser iniciar instâncias do Cloud Volumes ONTAP em qualquer região do AWS GovCloud (EUA).
* A AMI de pagamento conforme o uso da nuvem da ONTAP não é compatível na região AWS GovCloud (EUA).
* Quando implantado na região AWS GovCloud (EUA), o Cloud Manager não consegue descobrir clusters do ONTAP em uma configuração de armazenamento privado do NetApp para Microsoft Azure ou em uma configuração de armazenamento privado do NetApp para SoftLayer.




=== A remoção e a reinstalação de volumes EBS não é suportada

Desconetar um volume do EBS de uma instância do ONTAP Cloud e anexá-lo novamente a outra instância do ONTAP Cloud não é suportado. Você deve usar o Cloud Manager para replicar dados entre instâncias.



=== Limitações de criptografia

* O LUN Move não é suportado em sistemas que tenham a encriptação ONTAP Cloud ativada.
* A nuvem ONTAP envia chaves de criptografia para gerenciadores de chaves, mesmo para agregados que não foram criados.
+
Você deve excluir manualmente as chaves dos gerenciadores de chaves.


